import './hero';
import './section';
import './feature';
import './feature/feature-item';
import './posts';
import './accordion';
import './accordion/accordion-item';
import './pricing';
import './pricing/pricing-item';
